#pragma once

#define SAMPLE_INTERVAL_MS 500

#define RPM_WARNING 1500
#define RPM_CRITICAL 500

#define CURRENT_WARNING 8
#define CURRENT_CRITICAL 12

#define TEMP_WARNING 65
#define TEMP_CRITICAL 80

#define VIB_WARNING 0.5
#define VIB_CRITICAL 0.8

#define EMA_ALPHA 0.05

#define FUSION_THRESHOLD 0.50
