/**
 * ============================================================
 *  HYBRID EDGE-AI MOTOR FAULT DETECTION & SELF-HEALING SYSTEM
 *  Patent-Ready Firmware — ESP32
 * ============================================================
 *
 * PATENT CLAIMS IMPLEMENTED:
 *  Claim 1  — Multi-sensor acquisition (IR + ACS712 + MPU6050 + DS18B20)
 *  Claim 2  — Edge-only inference (zero cloud dependency)
 *  Claim 3  — Weighted multi-modal anomaly fusion scoring
 *  Claim 4  — Explainable rule-sensor fault classification mapping
 *  Claim 5  — Severity-graduated corrective actuation
 *  Claim 6  — Persistent EEPROM fault event logging
 *  Claim 7  — Adaptive baseline updating from recovery outcomes
 *  Claim 8  — Physics-based cross-sensor validation
 *  Claim 9  — Dynamic thermal threshold with preventive speed reduction
 *  Claim 10 — Complete autonomous fault-recovery method
 *
 * HARDWARE:
 *  ESP32 DevKit V1
 *  IR speed sensor        → GPIO 34 (input, interrupt)
 *  ACS712-30A             → GPIO 35 (ADC)
 *  MPU6050                → I2C SDA=21, SCL=22
 *  DS18B20                → GPIO 4  (OneWire)
 *  Motor relay / PWM      → GPIO 25
 *  Status LED             → GPIO 2
 *
 * REQUIRED LIBRARIES:
 *  OneWire, DallasTemperature, Wire, MPU6050 (jrowberg),
 *  EEPROM (built-in), math (built-in)
 *
 *  ML model header "one_class_svm_model.h" generated from
 *  Google Colab using micromlgen (OneClassSVM) — place in same sketch folder.
 * ============================================================
 */

// ─── INCLUDES ───────────────────────────────────────────────
#include <Arduino.h>
#include <Wire.h>
#include <EEPROM.h>
#include <math.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include "MPU6050.h"
#include "one_class_svm_model.h"       // generated by Colab + micromlgen (OneClassSVM)

// ─── PIN DEFINITIONS ────────────────────────────────────────
#define IR_SENSOR_PIN      34   // IRAM-safe interrupt pin
#define ACS712_PIN         35   // ADC1 channel
#define ONE_WIRE_BUS       4    // DS18B20 data pin
#define MOTOR_PWM_PIN      25   // PWM / relay control
#define STATUS_LED_PIN     2    // Onboard LED

// ─── PWM CHANNEL CONFIG ─────────────────────────────────────
#define PWM_CHANNEL        0
#define PWM_FREQ_HZ        20000
#define PWM_RESOLUTION     8    // 8-bit → 0-255

// ─── MOTOR NORMAL OPERATING ENVELOPE (Claim 7 — adaptive) ───
#define BASELINE_RPM_DEFAULT     1800.0f
#define BASELINE_CURRENT_DEFAULT 3.5f    // Amperes
#define BASELINE_VIBRATION_DEFAULT 0.15f // g-force RMS
#define BASELINE_TEMP_DEFAULT    40.0f   // °C

// ─── STATIC FAULT THRESHOLDS ────────────────────────────────
#define TEMP_WARNING_C      65.0f   // Claim 9 — preventive reduction
#define TEMP_CRITICAL_C     80.0f   // Claim 9 — emergency stop
#define CURRENT_OVERCURRENT 8.0f    // 8A → locked rotor
#define CURRENT_UNDERCURRENT 0.5f   // 0.5A → phase loss
#define RPM_OVERSPEED       2400.0f
#define RPM_STALL           50.0f   // near-zero → stall
#define VIBRATION_HIGH      0.80f   // g RMS → bearing fault

// ─── FUSION WEIGHTS (Claim 3 — explicitly defined) ──────────
//  Weights sum to 1.0 and are chosen based on fault observability:
//  - Vibration is most sensitive to mechanical faults
//  - Current reveals electrical faults
//  - Temperature has slower dynamics → lower weight
//  - RPM deviation is a secondary indicator
#define W_VIBRATION    0.35f
#define W_CURRENT      0.30f
#define W_RPM          0.20f
#define W_TEMPERATURE  0.15f

// ─── SEVERITY THRESHOLDS (Claim 5) ──────────────────────────
#define SCORE_NOMINAL    0.25f
#define SCORE_WARNING    0.50f
#define SCORE_CRITICAL   0.75f

// ─── EEPROM LAYOUT (Claim 6 — persistent logging) ───────────
#define EEPROM_SIZE          512
#define EEPROM_MAGIC_ADDR    0      // 2 bytes — 0xDEAD if initialized
#define EEPROM_COUNT_ADDR    2      // 2 bytes — number of logged events
#define EEPROM_LOG_START     4      // fault records start here
#define MAX_FAULT_RECORDS    20     // each record = 20 bytes
#define EEPROM_MAGIC_VAL     0xDEAD

// ─── ADAPTIVE BASELINE LEARNING RATE (Claim 7) ──────────────
#define ALPHA_LEARN  0.05f   // EMA coefficient; small = slow stable learning

// ─── TIMING ─────────────────────────────────────────────────
#define SAMPLE_INTERVAL_MS   500    // 2 Hz main loop
#define RPM_PULSE_TIMEOUT_MS 3000   // stall detection
#define BASELINE_UPDATE_EVERY 100   // update after N consecutive normal cycles

// ─── EEPROM FAULT RECORD STRUCT (20 bytes) ──────────────────
struct __attribute__((packed)) FaultRecord {
    uint32_t timestamp_s;    // uptime seconds
    uint8_t  fault_code;     // bitmask: bit0=RPM, bit1=Current, bit2=Vib, bit3=Temp
    uint8_t  severity;       // 1=Warning, 2=Critical, 3=Emergency
    float    score;          // fusion score at fault time
    float    rpm_at_fault;
    uint8_t  action_taken;   // 0=none, 1=reduce, 2=stop, 3=restart
    uint8_t  recovery_ok;    // 1 = recovered, 0 = manual needed
};  // total: 4+1+1+4+4+1+1 = 16 bytes → pad to 20

// ─── SENSOR DATA STRUCT ─────────────────────────────────────
struct SensorData {
    float rpm;
    float current_A;
    float vibration_g;
    float temperature_C;
    bool  valid;
};

// ─── OPERATIONAL BASELINE (Claim 7 — adaptive) ──────────────
struct Baseline {
    float rpm;
    float current_A;
    float vibration_g;
    float temperature_C;
};

// ─── GLOBAL STATE ───────────────────────────────────────────
volatile uint32_t g_pulseCount    = 0;
volatile uint32_t g_lastPulseMs   = 0;
uint8_t           g_motorDuty     = 255;   // full speed by default
uint16_t          g_faultCount    = 0;
uint32_t          g_normalCycles  = 0;
bool              g_motorRunning  = true;

Baseline g_baseline = {
    BASELINE_RPM_DEFAULT,
    BASELINE_CURRENT_DEFAULT,
    BASELINE_VIBRATION_DEFAULT,
    BASELINE_TEMP_DEFAULT
};

MPU6050   g_mpu;
OneWire   g_oneWire(ONE_WIRE_BUS);
DallasTemperature g_tempSensor(&g_oneWire);

// ─── ISR: IR PULSE COUNTER ──────────────────────────────────
void IRAM_ATTR irPulseISR() {
    g_pulseCount++;
    g_lastPulseMs = millis();
}

// ============================================================
//  CLAIM 1 — MULTI-SENSOR ACQUISITION
// ============================================================

/**
 * Read RPM from IR reflective sensor via pulse counting.
 * Assumes motor disk has 1 reflective slot per revolution.
 */
float readRPM() {
    static uint32_t lastMs = 0;
    uint32_t now = millis();
    uint32_t dt  = now - lastMs;
    if (dt < SAMPLE_INTERVAL_MS) return -1.0f; // not ready

    noInterrupts();
    uint32_t pulses = g_pulseCount;
    g_pulseCount = 0;
    interrupts();

    lastMs = now;

    // Stall detection: no pulse for RPM_PULSE_TIMEOUT_MS
    if ((now - g_lastPulseMs) > RPM_PULSE_TIMEOUT_MS && g_motorRunning) {
        return 0.0f;  // stall
    }

    // RPM = (pulses per interval) * (60000 / interval_ms)
    float rpm = (float)pulses * (60000.0f / (float)dt);
    return rpm;
}

/**
 * Read phase current via ACS712-30A.
 * Sensitivity: 66 mV/A, midpoint = 2.5 V (512 ADC counts at 3.3V ref)
 */
float readCurrent() {
    const int SAMPLES = 20;
    long sum = 0;
    for (int i = 0; i < SAMPLES; i++) {
        sum += analogRead(ACS712_PIN);
        delayMicroseconds(100);
    }
    float adc_avg = (float)sum / SAMPLES;
    // ESP32 ADC: 12-bit, 3.3V reference
    float voltage  = (adc_avg / 4095.0f) * 3.3f;
    float current  = (voltage - 1.65f) / 0.066f;  // ACS712-30A: 66mV/A
    return fabsf(current);
}

/**
 * Read vibration g-force RMS from MPU6050 accelerometer.
 * Computes RMS over 50 samples to capture vibration energy.
 */
float readVibration() {
    const int SAMPLES = 50;
    float sumSq = 0.0f;
    int16_t ax, ay, az, gx, gy, gz;

    for (int i = 0; i < SAMPLES; i++) {
        g_mpu.getMotion6(&ax, &ay, &az, &gx, &gy, &gz);
        // Scale to g-force (MPU6050 ±2g default → LSB = 16384)
        float ax_g = ax / 16384.0f;
        float ay_g = ay / 16384.0f;
        float az_g = az / 16384.0f;
        float magnitude = sqrtf(ax_g*ax_g + ay_g*ay_g + az_g*az_g) - 1.0f; // remove gravity
        sumSq += magnitude * magnitude;
        delayMicroseconds(500);
    }
    return sqrtf(sumSq / SAMPLES);
}

/**
 * Read motor winding temperature via DS18B20 (Claim 9).
 */
float readTemperature() {
    g_tempSensor.requestTemperatures();
    float t = g_tempSensor.getTempCByIndex(0);
    if (t == DEVICE_DISCONNECTED_C) {
        Serial.println("[WARN] DS18B20 disconnected — using 25°C default");
        return 25.0f;
    }
    return t;
}

// ============================================================
//  CLAIM 8 — PHYSICS-BASED CROSS-SENSOR VALIDATION
// ============================================================
/**
 * Validates that sensor readings are physically consistent with
 * known motor electromechanical relationships:
 *
 *  Rule A: High current WITH low RPM → locked rotor (consistent fault)
 *  Rule B: High vibration WITHOUT current → sensor noise (likely spurious)
 *  Rule C: High temperature WITH nominal current → cooling failure
 *  Rule D: RPM overspeed WITH nominal current → encoder/tachometer error
 *
 * Returns a confidence multiplier in [0.5, 1.0].
 * A low multiplier reduces the fusion score to prevent false alarms.
 */
float physicsValidationMultiplier(const SensorData& s) {
    float confidence = 1.0f;

    // Rule A: Locked rotor — high current + zero RPM → physically consistent
    bool highCurrent = (s.current_A > CURRENT_OVERCURRENT * 0.6f);
    bool lowRPM      = (s.rpm < RPM_STALL);
    if (highCurrent && lowRPM) {
        confidence *= 1.0f;  // no penalty — consistent fault signature
    }

    // Rule B: High vibration but current is normal → possible sensor artifact
    bool highVibration = (s.vibration_g > VIBRATION_HIGH * 0.7f);
    bool normalCurrent = (s.current_A < g_baseline.current_A * 1.2f);
    bool normalRPM     = (fabsf(s.rpm - g_baseline.rpm) < g_baseline.rpm * 0.1f);
    if (highVibration && normalCurrent && normalRPM) {
        confidence *= 0.65f; // penalty — vibration alone needs corroboration
    }

    // Rule C: High temperature with nominal current → cooling path fault
    bool highTemp = (s.temperature_C > TEMP_WARNING_C);
    if (highTemp && normalCurrent && normalRPM) {
        confidence *= 0.85f; // plausible but slightly suspicious without load
    }

    // Rule D: Overspeed with nominal current — likely tachometer artifact
    bool overSpeed = (s.rpm > RPM_OVERSPEED);
    if (overSpeed && normalCurrent) {
        confidence *= 0.50f; // strong penalty — physically implausible
    }

    // Clamp
    if (confidence < 0.5f) confidence = 0.5f;
    return confidence;
}

// ============================================================
//  CLAIM 3 — WEIGHTED MULTI-MODAL ANOMALY FUSION SCORE
// ============================================================
/**
 * Computes a normalized anomaly score in [0.0, 1.0] using
 * sensor-specific normalized deviations from adaptive baseline,
 * weighted by the predefined W_* constants.
 *
 * Also integrates the ML isolation forest anomaly flag
 * (from the deployed micromlgen model) as a binary correction.
 *
 * Claim 3 weight formula:
 *   score_i = |reading_i - baseline_i| / baseline_i
 *   fusion  = (W_VIB * score_vib + W_CUR * score_cur +
 *              W_RPM * score_rpm + W_TMP * score_tmp)
 *             * physics_confidence
 */
float computeFusionScore(const SensorData& s, bool mlAnomalyFlag) {
    // Normalized deviation per sensor
    float s_rpm   = fabsf(s.rpm - g_baseline.rpm)          / (g_baseline.rpm + 1e-6f);
    float s_cur   = fabsf(s.current_A - g_baseline.current_A) / (g_baseline.current_A + 1e-6f);
    float s_vib   = fabsf(s.vibration_g - g_baseline.vibration_g) / (g_baseline.vibration_g + 1e-6f);
    float s_tmp   = fabsf(s.temperature_C - g_baseline.temperature_C) / (g_baseline.temperature_C + 1e-6f);

    // Clamp individual scores to [0, 1]
    s_rpm = (s_rpm > 1.0f) ? 1.0f : s_rpm;
    s_cur = (s_cur > 1.0f) ? 1.0f : s_cur;
    s_vib = (s_vib > 1.0f) ? 1.0f : s_vib;
    s_tmp = (s_tmp > 1.0f) ? 1.0f : s_tmp;

    // Weighted fusion
    float fusion = W_VIBRATION   * s_vib
                 + W_CURRENT     * s_cur
                 + W_RPM         * s_rpm
                 + W_TEMPERATURE * s_tmp;

    // Physics cross-validation multiplier (Claim 8)
    float physMul = physicsValidationMultiplier(s);
    fusion *= physMul;

    // ML isolation forest boost: if model flags anomaly, elevate score
    if (mlAnomalyFlag) {
        fusion = fusion * 0.5f + 0.5f;  // blend toward 0.5 minimum
    }

    return (fusion > 1.0f) ? 1.0f : fusion;
}

// ============================================================
//  ML INFERENCE — OneClassSVM (micromlgen C model)
//  Claim 2: runs entirely on ESP32, no cloud call
// ============================================================
/**
 * Runs the C-array OneClassSVM model generated by Colab.
 * Returns true if the sample is classified as anomalous.
 *
 * Model: sklearn OneClassSVM(kernel='rbf', gamma=0.001, nu=0.03)
 * Trained on normal motor data only (unsupervised anomaly detection).
 * Exported via micromlgen → oneClassSVMPredict() in one_class_svm_model.h
 */
bool runOneClassSVM(const SensorData& s) {
    // Feature vector must match training order:
    // [rpm, current, vibration, temperature] — raw sensor units
    // normalizeFeatures() is called inside oneClassSVMPredict()
    float features[4] = {
        s.rpm,
        s.current_A,
        s.vibration_g,
        s.temperature_C
    };

    // oneClassSVMPredict() is defined in one_class_svm_model.h
    // Returns sklearn convention: -1 = anomaly, 1 = normal
    int prediction = oneClassSVMPredict(features);
    return (prediction == -1);  // true = anomaly detected
}

// ============================================================
//  CLAIM 4 — EXPLAINABLE FAULT CLASSIFICATION
// ============================================================
// Fault type bitmask
#define FAULT_NONE          0x00
#define FAULT_STALL         0x01  // bit 0 — RPM near zero
#define FAULT_OVERSPEED     0x02  // bit 1 — RPM exceeds envelope
#define FAULT_OVERCURRENT   0x04  // bit 2 — current > threshold
#define FAULT_PHASE_LOSS    0x08  // bit 3 — current < threshold
#define FAULT_BEARING       0x10  // bit 4 — high vibration
#define FAULT_THERMAL       0x20  // bit 5 — DS18B20 overtemp
#define FAULT_ML_ANOMALY    0x40  // bit 6 — ML model flagged

struct FaultClassification {
    uint8_t fault_code;
    uint8_t severity;       // 1=Warning, 2=Critical, 3=Emergency
    char    cause[80];      // human-readable explanation
};

/**
 * Maps sensor readings to fault type with human-readable cause string.
 * Each rule is directly traceable to a specific sensor (Claim 4).
 */
FaultClassification classifyFault(const SensorData& s, float score, bool mlFlag) {
    FaultClassification fc;
    fc.fault_code = FAULT_NONE;
    fc.severity   = 0;
    snprintf(fc.cause, sizeof(fc.cause), "Normal operation");

    // — Thermal check first (highest priority, Claim 9) —
    if (s.temperature_C >= TEMP_CRITICAL_C) {
        fc.fault_code |= FAULT_THERMAL;
        fc.severity = 3;
        snprintf(fc.cause, sizeof(fc.cause),
            "EMERGENCY: Thermal overload %.1f°C (DS18B20, limit %.0f°C)",
            s.temperature_C, TEMP_CRITICAL_C);
        return fc;
    }
    if (s.temperature_C >= TEMP_WARNING_C) {
        fc.fault_code |= FAULT_THERMAL;
        fc.severity = max(fc.severity, (uint8_t)2);
        snprintf(fc.cause, sizeof(fc.cause),
            "WARNING: High winding temperature %.1f°C — cooling degraded",
            s.temperature_C);
    }

    // — Locked rotor / stall —
    if (s.rpm <= RPM_STALL && g_motorRunning) {
        fc.fault_code |= FAULT_STALL;
        fc.severity = max(fc.severity, (uint8_t)3);
        snprintf(fc.cause, sizeof(fc.cause),
            "EMERGENCY: Motor stall — RPM=%.0f (IR sensor), possible jam or supply loss",
            s.rpm);
    }

    // — Overspeed —
    if (s.rpm > RPM_OVERSPEED) {
        fc.fault_code |= FAULT_OVERSPEED;
        fc.severity = max(fc.severity, (uint8_t)2);
        snprintf(fc.cause, sizeof(fc.cause),
            "CRITICAL: Overspeed %.0f RPM (limit %.0f) — load shedding or governor fail",
            s.rpm, RPM_OVERSPEED);
    }

    // — Overcurrent (locked rotor electrical signature) —
    if (s.current_A > CURRENT_OVERCURRENT) {
        fc.fault_code |= FAULT_OVERCURRENT;
        fc.severity = max(fc.severity, (uint8_t)3);
        snprintf(fc.cause, sizeof(fc.cause),
            "EMERGENCY: Overcurrent %.2fA (ACS712, limit %.1fA) — check for short or locked rotor",
            s.current_A, CURRENT_OVERCURRENT);
    }

    // — Phase loss / open circuit —
    if (s.current_A < CURRENT_UNDERCURRENT && g_motorRunning) {
        fc.fault_code |= FAULT_PHASE_LOSS;
        fc.severity = max(fc.severity, (uint8_t)2);
        snprintf(fc.cause, sizeof(fc.cause),
            "CRITICAL: Phase loss — current %.2fA below %.1fA threshold (ACS712)",
            s.current_A, CURRENT_UNDERCURRENT);
    }

    // — Bearing / mechanical vibration fault —
    if (s.vibration_g > VIBRATION_HIGH) {
        fc.fault_code |= FAULT_BEARING;
        fc.severity = max(fc.severity, (uint8_t)2);
        snprintf(fc.cause, sizeof(fc.cause),
            "CRITICAL: Excessive vibration %.3fg RMS (MPU6050) — bearing wear or imbalance",
            s.vibration_g);
    }

    // — ML OneClassSVM anomaly (Claim 2 — edge inference) —
    if (mlFlag && fc.fault_code == FAULT_NONE) {
        fc.fault_code |= FAULT_ML_ANOMALY;
        fc.severity = max(fc.severity, (uint8_t)1);
        snprintf(fc.cause, sizeof(fc.cause),
            "WARNING: Anomaly detected by edge ML model (OneClassSVM) — score=%.3f",
            score);
    }

    return fc;
}

// ============================================================
//  CLAIM 5 — SEVERITY-GRADUATED CORRECTIVE ACTUATION
// ============================================================
/**
 * Takes a graduated corrective action based on severity level:
 *  Severity 0 → No action (nominal)
 *  Severity 1 → Warning: log event, blink LED, no speed change
 *  Severity 2 → Critical: reduce motor speed to 50%, alert
 *  Severity 3 → Emergency: full stop, wait for cool-down, auto-restart
 *
 * Returns the action code logged in EEPROM.
 */
uint8_t executeCorrectiveAction(const FaultClassification& fc, const SensorData& s) {
    uint8_t action = 0;

    switch (fc.severity) {
        case 0:
            // Nominal — ensure motor at full speed
            g_motorDuty = 255;
            ledcWrite(PWM_CHANNEL, g_motorDuty);
            g_motorRunning = true;
            action = 0;
            break;

        case 1: // WARNING — log and alert only
            Serial.printf("[WARN]  Fault code: 0x%02X | %s\n", fc.fault_code, fc.cause);
            // Blink LED twice
            for (int i = 0; i < 2; i++) {
                digitalWrite(STATUS_LED_PIN, HIGH); delay(200);
                digitalWrite(STATUS_LED_PIN, LOW);  delay(200);
            }
            action = 1;
            break;

        case 2: // CRITICAL — reduce to 50% duty
            g_motorDuty = 127;
            ledcWrite(PWM_CHANNEL, g_motorDuty);
            g_motorRunning = true;
            Serial.printf("[CRIT]  Fault code: 0x%02X | %s\n", fc.fault_code, fc.cause);
            Serial.println("[CRIT]  Motor speed reduced to 50%");
            // Claim 9: thermal-specific preventive reduction
            if (fc.fault_code & FAULT_THERMAL) {
                Serial.printf("[THERM] Preventive reduction at %.1f°C (threshold %.0f°C)\n",
                              s.temperature_C, TEMP_WARNING_C);
            }
            action = 2;
            break;

        case 3: // EMERGENCY — stop, cool-down, attempt restart
            g_motorDuty = 0;
            ledcWrite(PWM_CHANNEL, 0);
            g_motorRunning = false;
            Serial.printf("[EMRG]  Fault code: 0x%02X | %s\n", fc.fault_code, fc.cause);
            Serial.println("[EMRG]  Motor STOPPED. Waiting 10s cool-down...");

            // Rapid LED flash during cool-down
            for (int i = 0; i < 20; i++) {
                digitalWrite(STATUS_LED_PIN, HIGH); delay(250);
                digitalWrite(STATUS_LED_PIN, LOW);  delay(250);
            }

            // Auto-restart attempt
            Serial.println("[EMRG]  Attempting auto-restart...");
            g_motorDuty = 128;  // restart at 50%
            ledcWrite(PWM_CHANNEL, g_motorDuty);
            g_motorRunning = true;
            action = 3;
            break;
    }
    return action;
}

// ============================================================
//  CLAIM 6 — PERSISTENT EEPROM FAULT LOGGING
// ============================================================

void initEEPROM() {
    EEPROM.begin(EEPROM_SIZE);
    uint16_t magic;
    EEPROM.get(EEPROM_MAGIC_ADDR, magic);
    if (magic != EEPROM_MAGIC_VAL) {
        Serial.println("[EEPROM] First boot — initializing fault log.");
        EEPROM.put(EEPROM_MAGIC_ADDR, (uint16_t)EEPROM_MAGIC_VAL);
        uint16_t zero = 0;
        EEPROM.put(EEPROM_COUNT_ADDR, zero);
        EEPROM.commit();
    }
    EEPROM.get(EEPROM_COUNT_ADDR, g_faultCount);
    Serial.printf("[EEPROM] Loaded %u previous fault records.\n", g_faultCount);
}

void logFaultToEEPROM(const FaultClassification& fc, const SensorData& s,
                       float score, uint8_t action, bool recovered) {
    if (g_faultCount >= MAX_FAULT_RECORDS) {
        // Ring buffer: overwrite oldest record
        g_faultCount = 0;
    }

    FaultRecord rec;
    rec.timestamp_s  = millis() / 1000;
    rec.fault_code   = fc.fault_code;
    rec.severity     = fc.severity;
    rec.score        = score;
    rec.rpm_at_fault = s.rpm;
    rec.action_taken = action;
    rec.recovery_ok  = recovered ? 1 : 0;

    int addr = EEPROM_LOG_START + g_faultCount * sizeof(FaultRecord);
    EEPROM.put(addr, rec);
    g_faultCount++;
    EEPROM.put(EEPROM_COUNT_ADDR, g_faultCount);
    EEPROM.commit();

    Serial.printf("[EEPROM] Fault #%u logged at t=%us, code=0x%02X, score=%.3f\n",
                  g_faultCount, rec.timestamp_s, rec.fault_code, score);
}

void printFaultHistory() {
    Serial.printf("\n=== FAULT LOG (%u records) ===\n", g_faultCount);
    for (uint16_t i = 0; i < g_faultCount; i++) {
        FaultRecord rec;
        int addr = EEPROM_LOG_START + i * sizeof(FaultRecord);
        EEPROM.get(addr, rec);
        Serial.printf("[%02u] t=%us code=0x%02X sev=%u score=%.3f rpm=%.0f action=%u ok=%u\n",
                      i, rec.timestamp_s, rec.fault_code, rec.severity,
                      rec.score, rec.rpm_at_fault, rec.action_taken, rec.recovery_ok);
    }
    Serial.println("==============================\n");
}

// ============================================================
//  CLAIM 7 — ADAPTIVE BASELINE UPDATING
// ============================================================
/**
 * Updates the operational baseline using Exponential Moving Average (EMA)
 * after N consecutive normal (fault-free) cycles.
 *
 * This allows the system to self-calibrate to aging motors,
 * seasonal temperature drift, and load profile changes — making
 * future fault detection more accurate without manual recalibration.
 *
 * EMA formula: baseline_new = (1 - α) * baseline_old + α * reading
 */
void updateAdaptiveBaseline(const SensorData& s) {
    g_normalCycles++;
    if (g_normalCycles >= BASELINE_UPDATE_EVERY) {
        g_baseline.rpm         = (1.0f - ALPHA_LEARN) * g_baseline.rpm
                                  + ALPHA_LEARN * s.rpm;
        g_baseline.current_A   = (1.0f - ALPHA_LEARN) * g_baseline.current_A
                                  + ALPHA_LEARN * s.current_A;
        g_baseline.vibration_g = (1.0f - ALPHA_LEARN) * g_baseline.vibration_g
                                  + ALPHA_LEARN * s.vibration_g;
        g_baseline.temperature_C = (1.0f - ALPHA_LEARN) * g_baseline.temperature_C
                                  + ALPHA_LEARN * s.temperature_C;
        g_normalCycles = 0;

        Serial.printf("[BASE]  Baseline updated → RPM=%.1f, I=%.2fA, Vib=%.3fg, T=%.1f°C\n",
                      g_baseline.rpm, g_baseline.current_A,
                      g_baseline.vibration_g, g_baseline.temperature_C);
    }
}

// ============================================================
//  SENSOR VALIDATION HELPERS
// ============================================================
bool validateSensorRanges(const SensorData& s) {
    bool ok = true;
    if (s.rpm < 0 || s.rpm > 5000) {
        Serial.println("[VALID] RPM out of range — sensor error");
        ok = false;
    }
    if (s.current_A < 0 || s.current_A > 30) {
        Serial.println("[VALID] Current out of range — ACS712 error");
        ok = false;
    }
    if (s.vibration_g < 0 || s.vibration_g > 16) {
        Serial.println("[VALID] Vibration out of range — MPU6050 error");
        ok = false;
    }
    if (s.temperature_C < -10 || s.temperature_C > 150) {
        Serial.println("[VALID] Temperature out of range — DS18B20 error");
        ok = false;
    }
    return ok;
}

// ============================================================
//  SETUP
// ============================================================
void setup() {
    Serial.begin(115200);
    delay(500);
    Serial.println("\n==========================================");
    Serial.println(" Hybrid Edge-AI Motor Fault Detector");
    Serial.println(" Patent-Ready Firmware v1.0");
    Serial.println("==========================================\n");

    // GPIO
    pinMode(IR_SENSOR_PIN, INPUT_PULLUP);
    pinMode(STATUS_LED_PIN, OUTPUT);
    attachInterrupt(digitalPinToInterrupt(IR_SENSOR_PIN), irPulseISR, FALLING);

    // PWM motor control
    ledcSetup(PWM_CHANNEL, PWM_FREQ_HZ, PWM_RESOLUTION);
    ledcAttachPin(MOTOR_PWM_PIN, PWM_CHANNEL);
    ledcWrite(PWM_CHANNEL, 255);  // full speed at start

    // I2C + MPU6050
    Wire.begin(21, 22);
    g_mpu.initialize();
    if (!g_mpu.testConnection()) {
        Serial.println("[ERROR] MPU6050 not found! Check wiring.");
    } else {
        Serial.println("[OK]    MPU6050 connected.");
        g_mpu.setFullScaleAccelRange(MPU6050_ACCEL_FS_2);  // ±2g
        g_mpu.setDLPFMode(MPU6050_DLPF_BW_42);              // 42Hz LPF
    }

    // DS18B20
    g_tempSensor.begin();
    Serial.printf("[OK]    DS18B20 found: %d sensor(s).\n",
                  g_tempSensor.getDeviceCount());

    // EEPROM fault log
    initEEPROM();

    // Print previous fault history on boot
    if (g_faultCount > 0) {
        printFaultHistory();
    }

    Serial.println("\n[START] System initialized. Entering monitoring loop.\n");
    delay(1000);
}

// ============================================================
//  MAIN LOOP — CLAIM 10: AUTONOMOUS FAULT-RECOVERY METHOD
// ============================================================
/**
 * Implements the patented method:
 *  Step 1: Acquire multi-modal sensor signals
 *  Step 2: Physics-validate for noise rejection (Claim 8)
 *  Step 3: Run edge ML inference (Claim 2)
 *  Step 4: Compute weighted fusion anomaly score (Claim 3)
 *  Step 5: Classify fault type with explainable mapping (Claim 4)
 *  Step 6: Execute severity-graduated corrective action (Claim 5)
 *  Step 7: Log event to EEPROM (Claim 6)
 *  Step 8: Update adaptive baseline from normal cycles (Claim 7)
 */
void loop() {
    static uint32_t lastSampleMs = 0;
    uint32_t now = millis();
    if (now - lastSampleMs < SAMPLE_INTERVAL_MS) return;
    lastSampleMs = now;

    // ── STEP 1: Acquire all sensor data ──────────────────────
    SensorData s;
    s.rpm           = readRPM();
    s.current_A     = readCurrent();
    s.vibration_g   = readVibration();
    s.temperature_C = readTemperature();  // DS18B20 — Claim 9
    s.valid         = validateSensorRanges(s);

    if (!s.valid) {
        Serial.println("[LOOP]  Sensor validation failed — skipping cycle.");
        return;
    }

    Serial.printf("[DATA]  RPM=%.0f | I=%.2fA | Vib=%.4fg | T=%.1f°C\n",
                  s.rpm, s.current_A, s.vibration_g, s.temperature_C);

    // ── STEP 3: Edge ML inference (Claim 2) ──────────────────
    bool mlAnomaly = runOneClassSVM(s);
    if (mlAnomaly) {
        Serial.println("[ML]    OneClassSVM: ANOMALY");
    }

    // ── STEP 4: Weighted fusion score (Claim 3) ───────────────
    float score = computeFusionScore(s, mlAnomaly);
    Serial.printf("[SCORE] Fusion score = %.4f\n", score);

    // ── STEP 5: Classify fault (Claim 4) ─────────────────────
    FaultClassification fc = classifyFault(s, score, mlAnomaly);

    // ── STEP 6: Corrective action (Claim 5) ──────────────────
    uint8_t action = 0;
    if (fc.fault_code != FAULT_NONE || score >= SCORE_WARNING) {
        action = executeCorrectiveAction(fc, s);

        // ── STEP 7: Log to EEPROM (Claim 6) ──────────────────
        bool recovered = (action == 3);  // auto-restart = recovery attempt
        logFaultToEEPROM(fc, s, score, action, recovered);
        g_normalCycles = 0;  // reset normal cycle counter on any fault

    } else {
        // ── STEP 8: Update adaptive baseline (Claim 7) ────────
        updateAdaptiveBaseline(s);
    }

    // Claim 9: Thermal-specific dynamic threshold reduction
    // (independent of main fault score — acts as a safety backstop)
    if (s.temperature_C >= TEMP_CRITICAL_C && g_motorRunning) {
        Serial.printf("[THERM] EMERGENCY shutdown: T=%.1f°C >= %.0f°C\n",
                      s.temperature_C, TEMP_CRITICAL_C);
        ledcWrite(PWM_CHANNEL, 0);
        g_motorRunning = false;
    }

    // Status LED: solid ON = normal, OFF = stopped
    digitalWrite(STATUS_LED_PIN, g_motorRunning ? HIGH : LOW);

    Serial.println("─────────────────────────────────────");
}
