/**
 * one_class_svm_model.h
 * ─────────────────────────────────────────────────────────────
 * THIS FILE IS AUTO-GENERATED by running motor_fault_ML_colab.py
 * in Google Colab (Cell 6, updated to OneClassSVM), then downloading
 * the output file named "one_class_svm_model.h".
 *
 * WHY OneClassSVM instead of IsolationForest?
 *  micromlgen does NOT support IsolationForest export.
 *  OneClassSVM (kernel=rbf) IS supported and produces a compact
 *  C function that fits comfortably in ESP32 flash.
 *
 * HOW TO GENERATE THE REAL MODEL:
 *  1. Open Google Colab: https://colab.research.google.com
 *  2. Run all cells of motor_fault_ML_colab.py in sequence.
 *  3. Cell 6 (OneClassSVM) will call:
 *         port(oc_svm_sklearn, classname='OneClassSVM')
 *     and save "one_class_svm_model.h" automatically.
 *  4. In the Colab left panel → Files → download one_class_svm_model.h
 *  5. Place this file in the SAME FOLDER as motor_fault_detector.ino
 *  6. Replace EVERYTHING below "BEGIN PLACEHOLDER" with the downloaded file.
 *
 * SCALER CONSTANTS — UPDATE THESE FROM COLAB CELL 5 OUTPUT:
 *  After running Cell 5, Colab prints lines like:
 *    #define SCALER_MEAN_RPM  1801.9201f
 *  Copy those exact values here to match your trained model.
 *
 * GENERATED FUNCTION SIGNATURE (do not change — .ino calls this):
 *  int oneClassSVMPredict(float* x);
 *  Returns: -1 = anomaly, 1 = normal  (sklearn convention)
 *  Input:   float[4] = {rpm_scaled, current_scaled, vib_scaled, temp_scaled}
 * ─────────────────────────────────────────────────────────────
 */

#pragma once
#include <stdint.h>

// ─── SCALER CONSTANTS ────────────────────────────────────────
// Replace with values printed by Colab Cell 5 for YOUR trained model.
// These defaults match the synthetic dataset used in the Colab script.
#define SCALER_MEAN_RPM             1801.9201f
#define SCALER_STD_RPM              59.1986f
#define SCALER_MEAN_CURRENT_A       3.4904f
#define SCALER_STD_CURRENT_A        0.2522f
#define SCALER_MEAN_VIBRATION_G     0.1501f
#define SCALER_STD_VIBRATION_G      0.0205f
#define SCALER_MEAN_TEMPERATURE_C   39.9579f
#define SCALER_STD_TEMPERATURE_C    1.9665f

/**
 * normalizeFeatures()
 * Applies StandardScaler normalization identical to Colab training.
 * Must be called before oneClassSVMPredict().
 *
 * @param raw    float[4] = {rpm, current_A, vibration_g, temperature_C}  (raw sensor units)
 * @param scaled float[4] output — z-score normalized values
 */
inline void normalizeFeatures(float* raw, float* scaled) {
    scaled[0] = (raw[0] - SCALER_MEAN_RPM)           / SCALER_STD_RPM;
    scaled[1] = (raw[1] - SCALER_MEAN_CURRENT_A)     / SCALER_STD_CURRENT_A;
    scaled[2] = (raw[2] - SCALER_MEAN_VIBRATION_G)   / SCALER_STD_VIBRATION_G;
    scaled[3] = (raw[3] - SCALER_MEAN_TEMPERATURE_C) / SCALER_STD_TEMPERATURE_C;
}

// ─────────────────────────────────────────────────────────────
// BEGIN PLACEHOLDER
// Replace EVERYTHING from here to end-of-file with the
// micromlgen-generated content from Colab (one_class_svm_model.h).
// ─────────────────────────────────────────────────────────────

/**
 * PLACEHOLDER: Mahalanobis-distance fallback so the sketch compiles
 * and behaves sensibly before the real OneClassSVM model is available.
 *
 * This stub:
 *  - Applies the same normalization as the real model
 *  - Uses χ²(0.995, df=4) = 11.97 as the anomaly boundary
 *    (equivalent to Mahalanobis distance > 3.46 standard deviations)
 *  - Returns sklearn convention: -1 = anomaly, 1 = normal
 *
 * Performance of this stub:
 *  Good for: stall, overspeed, overcurrent, phase loss, thermal faults
 *  Weak for: subtle ML-only drift (needs real OneClassSVM for that)
 *
 * @param features  float[4] = {rpm_raw, current_raw, vib_raw, temp_raw}
 * @return -1 if anomaly, 1 if normal
 */
int oneClassSVMPredict(float* features) {
    float scaled[4];
    normalizeFeatures(features, scaled);

    // Sum of squared z-scores = Mahalanobis² (assuming diagonal covariance)
    float mah_sq = 0.0f;
    mah_sq += scaled[0] * scaled[0];   // RPM deviation²
    mah_sq += scaled[1] * scaled[1];   // Current deviation²
    mah_sq += scaled[2] * scaled[2];   // Vibration deviation²
    mah_sq += scaled[3] * scaled[3];   // Temperature deviation²

    // χ²(0.995, df=4) = 11.97 → Mahalanobis distance threshold = sqrt(11.97) ≈ 3.46
    return (mah_sq > 11.97f) ? -1 : 1;
}

// ─────────────────────────────────────────────────────────────
// END PLACEHOLDER
// ─────────────────────────────────────────────────────────────
